import { Meta, StoryObj } from "@storybook/react";
import ProductSpecification from "./specification.component";

const meta: Meta<typeof ProductSpecification> = {
  title: "Product Specification",
  component: ProductSpecification,
  tags: ["autodocs"],
};

export default meta;

type Story = StoryObj<typeof ProductSpecification>;

const dataSet = [
  {
    id: 26,
    parent_id: null,
    isTitle: false,
    name: "Housing",
    numeric_value: null,
    text_value: "0805",
    unit_id: -1,
    unit_base_id: -1,
    unit_name: "NO_UNIT",
    position: 2,
  },
  {
    id: 1,
    parent_id: null,
    isTitle: false,
    name: "Resistance",
    numeric_value: 47,
    text_value: null,
    unit_id: 1,
    unit_base_id: 1,
    unit_name: "Ohm",
    position: 3,
  },
  {
    id: 2,
    parent_id: null,
    isTitle: false,
    name: "Tolerance",
    numeric_value: 1,
    text_value: null,
    unit_id: 7,
    unit_base_id: 7,
    unit_name: "%",
    position: 0,
  },
  {
    id: 17,
    parent_id: null,
    isTitle: false,
    name: "Power",
    numeric_value: 0.125,
    text_value: null,
    unit_id: 9,
    unit_base_id: 9,
    unit_name: "W",
    position: 1,
  },
];

const attributeSet = [
  {
    id: 23,
    parent_id: null,
    unit_id: null,
    name: "General",
    isTitle: true,
  },
  {
    id: 25,
    parent_id: null,
    unit_id: null,
    name: "Connectivity",
    isTitle: true,
  },
  {
    id: 10,
    parent_id: null,
    unit_id: 14,
    name: "Raster",
    isTitle: false,
  },
  {
    id: 24,
    parent_id: null,
    unit_id: 27,
    name: "Operating Temperature",
    isTitle: false,
  },
  {
    id: 1,
    parent_id: null,
    unit_id: 1,
    name: "Resistance",
    isTitle: false,
  },
  {
    id: 2,
    parent_id: null,
    unit_id: 7,
    name: "Tolerance",
    isTitle: false,
  },
  {
    id: 3,
    parent_id: null,
    unit_id: 5,
    name: "Forward voltage",
    isTitle: false,
  },
  {
    id: 4,
    parent_id: null,
    unit_id: 11,
    name: "Current",
    isTitle: false,
  },
  {
    id: 5,
    parent_id: null,
    unit_id: 5,
    name: "min. Voltage",
    isTitle: false,
  },
  {
    id: 6,
    parent_id: null,
    unit_id: 5,
    name: "max. Voltage",
    isTitle: false,
  },
  {
    id: 7,
    parent_id: null,
    unit_id: 5,
    name: "Voltage",
    isTitle: false,
  },
  {
    id: 8,
    parent_id: null,
    unit_id: 11,
    name: "min. Current",
    isTitle: false,
  },
  {
    id: 9,
    parent_id: null,
    unit_id: 11,
    name: "max. Current",
    isTitle: false,
  },
  {
    id: 11,
    parent_id: null,
    unit_id: 5,
    name: "Control voltage ",
    isTitle: false,
  },
  {
    id: 12,
    parent_id: null,
    unit_id: 11,
    name: "Switching current",
    isTitle: false,
  },
  {
    id: 13,
    parent_id: null,
    unit_id: 5,
    name: "Switching voltage",
    isTitle: false,
  },
  {
    id: 14,
    parent_id: null,
    unit_id: 18,
    name: "Frequency",
    isTitle: false,
  },
  {
    id: 15,
    parent_id: null,
    unit_id: 18,
    name: "min. Frequency",
    isTitle: false,
  },
  {
    id: 16,
    parent_id: null,
    unit_id: 18,
    name: "max. Frequency",
    isTitle: false,
  },
  {
    id: 17,
    parent_id: null,
    unit_id: 9,
    name: "Power",
    isTitle: false,
  },
  {
    id: 18,
    parent_id: null,
    unit_id: 9,
    name: "min. Power",
    isTitle: false,
  },
  {
    id: 19,
    parent_id: null,
    unit_id: 9,
    name: "max. Power",
    isTitle: false,
  },
  {
    id: 20,
    parent_id: null,
    unit_id: 9,
    name: "Switching power",
    isTitle: false,
  },
  {
    id: 21,
    parent_id: null,
    unit_id: 11,
    name: "Collector current",
    isTitle: false,
  },
  {
    id: 22,
    parent_id: null,
    unit_id: 22,
    name: "Capacity",
    isTitle: false,
  },
];

const unitSet = [
  {
    id: 1,
    parent_id: 1,
    name: "Ohm",
    factor: 1,
  },
  {
    id: 2,
    parent_id: 1,
    name: "kOhm",
    factor: 1000,
  },
  {
    id: 3,
    parent_id: 1,
    name: "MOhm",
    factor: 1000000,
  },
  {
    id: 4,
    parent_id: 5,
    name: "mV",
    factor: 0.001,
  },
  {
    id: 5,
    parent_id: 5,
    name: "V",
    factor: 1,
  },
  {
    id: 6,
    parent_id: 5,
    name: "kV",
    factor: 1000,
  },
  {
    id: 7,
    parent_id: 7,
    name: "%",
    factor: 1,
  },
  {
    id: 8,
    parent_id: 9,
    name: "mW",
    factor: 0.001,
  },
  {
    id: 9,
    parent_id: 9,
    name: "W",
    factor: 1,
  },
  {
    id: 10,
    parent_id: 9,
    name: "kW",
    factor: 1000,
  },
  {
    id: 11,
    parent_id: 11,
    name: "A",
    factor: 1,
  },
  {
    id: 12,
    parent_id: 11,
    name: "mA",
    factor: 0.001,
  },
  {
    id: 13,
    parent_id: 11,
    name: "uA",
    factor: 0.000001,
  },
  {
    id: 14,
    parent_id: 14,
    name: "m",
    factor: 1,
  },
  {
    id: 15,
    parent_id: 14,
    name: "mm",
    factor: 0.001,
  },
  {
    id: 16,
    parent_id: 14,
    name: "um",
    factor: 0.000001,
  },
  {
    id: 17,
    parent_id: 14,
    name: "km",
    factor: 1000,
  },
  {
    id: 18,
    parent_id: 18,
    name: "Hz",
    factor: 1,
  },
  {
    id: 19,
    parent_id: 18,
    name: "kHz",
    factor: 1000,
  },
  {
    id: 20,
    parent_id: 18,
    name: "Mhz",
    factor: 1000000,
  },
  {
    id: 21,
    parent_id: 18,
    name: "GHz",
    factor: 1000000000,
  },
  {
    id: 22,
    parent_id: 22,
    name: "F",
    factor: 1,
  },
  {
    id: 23,
    parent_id: 22,
    name: "mF",
    factor: 0.001,
  },
  {
    id: 24,
    parent_id: 22,
    name: "uF",
    factor: 0.000001,
  },
  {
    id: 25,
    parent_id: 22,
    name: "nF",
    factor: 1e-9,
  },
  {
    id: 26,
    parent_id: 22,
    name: "pF",
    factor: 1e-12,
  },
  {
    id: 27,
    parent_id: 27,
    name: "°C",
    factor: 1,
  },
];

export const Standard: Story = {
  args: {
    title: "Specification",
    dataSet: dataSet,
    attributeSet: attributeSet,
    unitSet: unitSet,
  },
};
